var wins = 0;//win
var loses = 0;//lose

var set;//number
var total = 0;//scoreBox

var rubyNum = Math.floor(Math.random()*10)+1
console.log(rubyNum);
var sapphireNum = Math.floor(Math.random()*10)+1
var emeraldNum = Math.floor(Math.random()*10)+1
var topazNum = Math.floor(Math.random()*10)+1
console.log(sapphireNum);
console.log(emeraldNum);
console.log(topazNum);
//assign the randon numbers above to the images (class)
document.querySelector(".ruby").innerHTML = rubyNum;
document.querySelector(".sapphire").innerHTML = sapphireNum;
document.querySelector(".emerald").innerHTML = emeraldNum;
document.querySelector(".topaz").innerHTML = topazNum;
//assign random number for set number
var num = Math.floor(Math.random()*20)+30;
set = num;
console.log(set);

//create onlcick function to add the value of each img clicked
document.getElementByTagName("img").onclick = function(){

}

//match if the total value generated by the player matches the random set value

//win and lose, if/else

//reset set value and randomize img value






/*
//retieve the data-num from gems and setting to var, to be used later
var rubyNum = document.querySelector(".ruby").getAttribute("data-num");
var sapphireNum = document.querySelector(".sapphire").getAttribute("data-num");
var emeraldNum = document.querySelector(".emerald").getAttribute("data-num");
var topazNum = document.querySelector(".topaz").getAttribute("data-num");
//console.log(rubyNum);
//console.log(sapphireNum);
//console.log(emeraldNum);
//console.log(topazNum);
*/