var wins = 0;//win
var loses = 0;//lose

var set;//number
var total = 0;//scoreBox



var rubyNum = Math.floor(Math.random()*10)+1
console.log(rubyNum);
var sapphireNum = Math.floor(Math.random()*10)+1
var emeraldNum = Math.floor(Math.random()*10)+1
var topazNum = Math.floor(Math.random()*10)+1
console.log(sapphireNum);
console.log(emeraldNum);
console.log(topazNum);
//assign the randon numbers above to the images (class)
document.querySelector(".ruby").innerHTML = rubyNum;
document.querySelector(".sapphire").innerHTML = sapphireNum;
document.querySelector(".emerald").innerHTML = emeraldNum;
document.querySelector(".topaz").innerHTML = topazNum;
//assign random number for set number
function randomNum() {
	set = Math.floor(Math.random()*20)+30;
	return set;
}

var set = randomNum();
console.log(set);

//put random number generated into the number box
document.querySelector('.numBox').innerHTML = set;
//create onlcick function to add the value of each img clicked

function addNum(a) {
	if (a.getAttribute('class') == 'ruby'){
		total = total + rubyNum;
	}else if (a.getAttribute('class') == 'emerald'){
		total = total + emeraldNum;
	}else if (a.getAttribute('class') == 'sapphire'){
		total = total + sapphireNum;
	}else{
		total = total + topazNum;
	}
}

document.querySelectorAll("img").onclick = function(){
	randomNum();
	addNum();

}

//match if the total value generated by the player matches the random set value

//win and lose, if/else

//reset set value and randomize img value



/*
//retieve the data-num from gems and setting to var, to be used later
var rubyNum = document.querySelector(".ruby").getAttribute("data-num");
var sapphireNum = document.querySelector(".sapphire").getAttribute("data-num");
var emeraldNum = document.querySelector(".emerald").getAttribute("data-num");
var topazNum = document.querySelector(".topaz").getAttribute("data-num");
//console.log(rubyNum);
//console.log(sapphireNum);
//console.log(emeraldNum);
//console.log(topazNum);
*/